### ISSUE TITLE
Color scheme a bit aggressive

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/dls-handbook#74]
Does anyone else feel a bit accosted by the color scheme when you look at our jekyll site? What if we softened both the background and the link color a bit, not necessarily these exact hex values but here's a concept:

![Screen Shot 2023-03-02 at 9 29 06 AM](https://user-images.githubusercontent.com/845363/222457271-e7475e3a-c175-4f1b-8c1c-099ecf5ceebf.png)

link color here is #2aa9f7 and background is #272657

**Comment by tpendragon** [comment]
https://just-the-docs.github.io/just-the-docs/docs/customization/#custom-schemes docs on how to customize color scheme
